"""D31-11: the gate baseline, REGENERATED unconditionally and compared BYTE for BYTE.

SPEC R2 says "re-freeze the gate baseline if gold moved". As literally written that clause
is DEAD TEXT on a successful run: ``scripts.freeze_gate_baseline.compute_baseline`` filters
the scored population to ``models.deploy_gate.HOLDOUT_SEASONS`` -- a CONSTANT tuple, not
whatever gold happens to contain -- so adding a 2025 slice to gold cannot move the baseline
population, and a conditional whose condition is unreachable never runs.

Running the generator ANYWAY converts that vacuous conditional into an INDEPENDENT SECOND
PROOF of byte-identity, and the independence is the whole value. The fingerprint ladder in
``tests/integration/test_gold_rebuild_attribution.py`` proves 2021-2024 did not move by
hashing the parquet columns. This module proves the same thing through an entirely
different code path: the gate's OWN scoring loaders (``BacktestEngine._load_features`` and
``_load_closing_odds``), the deployed artifacts, ``models.clv.compute_clv_for_predictions``
and ``models.deploy_gate.per_season_clv``. Two proofs that share no machinery and agree are
worth more than one proof run twice. A DIFFERENCE here IS the gold-moved signal and stops
the phase.

The comparison is a STRING equality against the committed ``[baseline.*]`` block, not a
numeric tolerance. ``tests/integration/test_promote_models.py::
test_frozen_baseline_matches_rescore_all_fields`` already compares the parsed values field
by field within ``_FRESHNESS_TOL``; that is the right instrument for artifact drift and the
wrong one here, because a byte-identity claim asserted through a tolerance is not a
byte-identity claim. Both exist, and they are answering different questions.

THE SECOND ORDERING CONSTRAINT THIS MODULE CARRIES (31-RESEARCH LANDMINE-5). The generator
re-scores through ``_load_closing_odds``, which after Plan 31-11's ingest reads a WIDENED
odds table: four juice columns (``spread_ju_home``, ``spread_ju_away``, ``total_over_ju``,
``total_under_ju``) that were not on the frame when the baseline was frozen. If those extra
columns perturbed the per-season computation at all, the byte-identity proof would fail for
a reason that has nothing to do with gold, and the failure would read as a false alarm
about the very thing the proof exists to check. So the perturbation is DISPROVED here
rather than assumed away.

TEST CLASS: integration. The re-score needs gitignored runtime state -- the gold matrices
under ``data/`` and the deployed artifacts under ``artifacts/`` -- so on a checkout without
them these skip with REGISTERED reasons (``tests/conftest._EVIDENCE_SKIP_MARKERS``) and the
terminal summary names them. Every reason this module can emit is catalogued below and the
catalogue is checked against the module's own ``pytest.skip`` call sites by AST, so adding
a skip without registering its phrasing is a failure rather than an invisible non-run.

ASCII only, no emoji (CLAUDE.md hard constraint).
"""

from __future__ import annotations

import ast
from pathlib import Path

import pandas as pd
import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]

_GATE_TOML = REPO_ROOT / "config" / "gate.toml"
_GOLD_WP = REPO_ROOT / "data" / "gold" / "features_wp.parquet"
_ARTIFACTS_MANIFEST = REPO_ROOT / "artifacts" / "latest.json"
_SILVER_ODDS = REPO_ROOT / "data" / "silver" / "odds_snapshot.parquet"

# The second line of the generator's own rendered header. Located by CONTENT rather than by
# line number, so the extraction survives an edit anywhere above it in config/gate.toml.
_BLOCK_HEADER_LINE = (
    "# FROZEN BASELINE VALUES -- generated by scripts/freeze_gate_baseline.py"
)

# The window the deploy gate scores on. Restated here ONLY as the expected value of an
# assertion; the value under test is imported from models.deploy_gate inside each test, so
# this module cannot become a second source of truth for it.
_EXPECTED_HOLDOUT = (2021, 2022, 2023, 2024)

# The single unburned split. It is in gold after Plan 31-11's rebuild and must be ABSENT
# from every population the gate scores (D31-11).
_CLEAN_SPLIT_SEASON = 2025

_SKIP_REASONS_THIS_MODULE_CAN_EMIT = [
    (
        "canonical gold is not present at data/gold/features_wp.parquet, so the "
        "gate-baseline generator cannot re-score -- data/ is gitignored runtime state."
    ),
    (
        "the deployed artifact manifest is not present at artifacts/latest.json, so the "
        "gate-baseline generator has nothing to re-score."
    ),
    (
        "the widened odds table is not present at data/silver/odds_snapshot.parquet, so "
        "the juice-column perturbation control cannot run."
    ),
    (
        "the four juice columns are absent from the loaded odds frame, so the "
        "perturbation control would compare a frame with itself and prove nothing."
    ),
]


def _require_rescore_inputs() -> None:
    """Skip with a REGISTERED reason when the re-score's gitignored inputs are absent."""
    if not _GOLD_WP.is_file():
        pytest.skip(
            "canonical gold is not present at data/gold/features_wp.parquet, so the "
            "gate-baseline generator cannot re-score -- data/ is gitignored runtime state."
        )
    if not _ARTIFACTS_MANIFEST.is_file():
        pytest.skip(
            "the deployed artifact manifest is not present at artifacts/latest.json, so "
            "the gate-baseline generator has nothing to re-score."
        )


def _committed_baseline_block() -> str:
    """Return the committed ``[baseline.*]`` section of config/gate.toml, verbatim.

    Located by CONTENT: the generator's own header line is found, the block starts on the
    separator line immediately above it, and it runs to the last non-blank line of the
    file. Reading the file in text mode folds CRLF to LF, so the comparison is unaffected
    by this repository's ``core.autocrlf=true`` working-tree line endings.
    """
    lines = _GATE_TOML.read_text(encoding="utf-8").split("\n")

    try:
        header = lines.index(_BLOCK_HEADER_LINE)
    except (
        ValueError
    ) as error:  # pragma: no cover - a broken checkout, not a runtime case
        msg = (
            f"config/gate.toml no longer contains the generator's header line "
            f"{_BLOCK_HEADER_LINE!r}, so the committed baseline block cannot be located. "
            "The block must be written by pasting scripts/freeze_gate_baseline.py's output "
            "whole, header included."
        )
        raise AssertionError(msg) from error

    start = header - 1
    last = max(index for index, line in enumerate(lines) if line.strip())

    trailing = [line for line in lines[last + 1 :] if line.strip()]
    assert not trailing, (
        "config/gate.toml carries non-blank content after the [baseline.*] block "
        f"({trailing!r}). The extraction assumes the generated block ends the file; move "
        "the new content above the block or teach this helper where the block ends."
    )

    return "\n".join(lines[start : last + 1]) + "\n"


def _juice_columns() -> tuple[str, ...]:
    """The four juice columns, READ from the ingest contract rather than re-listed."""
    from scripts.ingest_historical_odds import JUICE_COLUMNS

    return tuple(JUICE_COLUMNS)


class TestTheRegeneratedBaselineIsByteIdenticalToTheCommittedOne:
    """The independent second proof that 2021-2024 gold did not move."""

    @pytest.mark.integration
    def test_the_generated_block_equals_the_committed_block_byte_for_byte(self) -> None:
        _require_rescore_inputs()
        from scripts.freeze_gate_baseline import compute_baseline, render_baseline_toml

        generated = render_baseline_toml(
            compute_baseline(artifacts_dir=REPO_ROOT / "artifacts")
        )
        committed = _committed_baseline_block()

        if generated != committed:
            generated_lines = generated.split("\n")
            committed_lines = committed.split("\n")
            first = next(
                (
                    index
                    for index in range(max(len(generated_lines), len(committed_lines)))
                    if generated_lines[index : index + 1]
                    != committed_lines[index : index + 1]
                ),
                0,
            )
            msg = (
                "the REGENERATED gate baseline block is not byte-identical to the block "
                "committed in config/gate.toml. This is the INDEPENDENT second proof that "
                "the 2021-2024 gold slice did not move, arriving through the gate's own "
                "scoring loaders rather than through the fingerprint -- so a difference IS "
                "the gold-moved signal and STOPS the phase. Do NOT re-freeze the baseline "
                "to make this pass: re-freezing would erase the evidence that gold moved. "
                f"First differing line ({first}): committed "
                f"{committed_lines[first : first + 1]!r} vs generated "
                f"{generated_lines[first : first + 1]!r}."
            )
            raise AssertionError(msg)

    @pytest.mark.integration
    def test_the_extraction_is_not_vacuous(self) -> None:
        """A comparison against an empty or partial block would pass for free."""
        committed = _committed_baseline_block()

        for target in ("wp", "ats", "ou"):
            assert f"[baseline.{target}.pooled]" in committed, (
                f"the extracted committed block carries no [baseline.{target}.pooled] "
                "table, so the byte-identity comparison is judging a fragment."
            )
            for season in _EXPECTED_HOLDOUT:
                assert f"[baseline.{target}.season.{season}]" in committed, (
                    f"the extracted committed block carries no "
                    f"[baseline.{target}.season.{season}] table."
                )
        assert _BLOCK_HEADER_LINE in committed
        assert committed.endswith("\n")


class TestTheWidenedOddsTableDoesNotPerturbTheBaseline:
    """LANDMINE-5, second ordering constraint: the four new juice columns are inert here.

    The generator re-scores through the closing-odds loader, which now sees four columns it
    did not see when the baseline was frozen. Proving they change nothing is what makes a
    byte-identity FAILURE unambiguous: it could then only mean gold moved.
    """

    @pytest.mark.integration
    def test_dropping_the_juice_columns_changes_no_per_season_figure(self) -> None:
        _require_rescore_inputs()
        if not _SILVER_ODDS.is_file():
            pytest.skip(
                "the widened odds table is not present at "
                "data/silver/odds_snapshot.parquet, so the juice-column perturbation "
                "control cannot run."
            )

        from backtest.diagnose import score_deployed_artifacts
        from backtest.engine import BacktestEngine
        from models.clv import compute_clv_for_predictions
        from models.deploy_gate import HOLDOUT_SEASONS, per_season_clv

        engine = BacktestEngine()
        odds = engine._load_closing_odds()

        juice = [column for column in _juice_columns() if column in odds.columns]
        if len(juice) != len(_juice_columns()):
            pytest.skip(
                "the four juice columns are absent from the loaded odds frame, so the "
                "perturbation control would compare a frame with itself and prove nothing."
            )

        narrowed = odds.drop(columns=juice)
        compared = 0
        for target in ("wp", "ats", "ou"):
            features = engine._load_features(target)
            in_holdout = (features["season"] >= HOLDOUT_SEASONS[0]) & (
                features["season"] <= HOLDOUT_SEASONS[-1]
            )
            gold_df: pd.DataFrame = features.loc[in_holdout].copy()

            # Score ONCE and reuse. The claim under test is about the ODDS frame, so
            # re-scoring per variant would introduce a second difference and weaken it.
            scored = score_deployed_artifacts(
                target, gold_df=gold_df, artifacts_dir=REPO_ROOT / "artifacts"
            )

            wide = compute_clv_for_predictions(scored, odds, target)
            thin = compute_clv_for_predictions(scored, narrowed, target)
            wide_valid = wide.loc[wide["has_closing_odds"]]
            thin_valid = thin.loc[thin["has_closing_odds"]]

            assert len(wide_valid) == len(thin_valid), (
                f"{target}: the widened odds frame admits {len(wide_valid)} scored rows "
                f"against {len(thin_valid)} for the narrowed one. The four juice columns "
                "changed the JOIN, not merely the frame's width."
            )

            wide_seasons = per_season_clv(wide_valid, target, seasons=HOLDOUT_SEASONS)
            thin_seasons = per_season_clv(thin_valid, target, seasons=HOLDOUT_SEASONS)
            assert set(wide_seasons) == set(thin_seasons)

            for season in sorted(wide_seasons):
                for key in ("n", "mean", "t", "p"):
                    assert wide_seasons[season][key] == thin_seasons[season][key], (
                        f"{target} season {season}: '{key}' is "
                        f"{wide_seasons[season][key]} with the four juice columns present "
                        f"and {thin_seasons[season][key]} without them. The added columns "
                        "perturb the per-season closing-line-value computation, so a "
                        "byte-identity failure could no longer be read as a gold move."
                    )
                    compared += 1

        # Guard the guard: a loop that silently compared nothing would pass for free.
        expected = 3 * len(HOLDOUT_SEASONS) * 4
        assert compared == expected, (
            f"the perturbation control compared {compared} per-season figures, not the "
            f"{expected} expected (3 targets x {len(HOLDOUT_SEASONS)} seasons x 4 keys)."
        )


class TestTheCleanSplitNeverEntersTheGate:
    """D31-11 / T-31-53: 2025 is in gold now, and must stay out of the gate's population.

    Adding 2025 to ``gate.seasons.holdout`` would drop the single-use clean split into the
    deploy gate's own population and burn it before the verdict run. The permanent guard on
    the configuration lives in ``tests/unit/test_deploy_gate.py``; what is asserted here is
    the consequence that guard exists FOR -- that the population the baseline generator
    actually scores contains no 2025 game, measured on the live gold this plan just widened.
    """

    def test_the_holdout_constant_is_exactly_the_four_tune_seasons(self) -> None:
        from models.deploy_gate import HOLDOUT_SEASONS

        assert tuple(HOLDOUT_SEASONS) == _EXPECTED_HOLDOUT, (
            f"models.deploy_gate.HOLDOUT_SEASONS is {tuple(HOLDOUT_SEASONS)}, not "
            f"{_EXPECTED_HOLDOUT}. The gate-baseline population is bounded by this "
            "constant, which is the only reason a 2025 gold slice cannot move the frozen "
            "baseline."
        )
        assert _CLEAN_SPLIT_SEASON not in HOLDOUT_SEASONS

    def test_the_committed_gate_configuration_agrees_with_the_constant(self) -> None:
        from models import deploy_gate

        cfg = deploy_gate.load_gate_config(_GATE_TOML)
        holdout = tuple(cfg["gate"]["seasons"]["holdout"])
        assert holdout == _EXPECTED_HOLDOUT, (
            f"config/gate.toml gate.seasons.holdout is {holdout}, not {_EXPECTED_HOLDOUT}."
        )
        assert _CLEAN_SPLIT_SEASON not in holdout, (
            f"season {_CLEAN_SPLIT_SEASON} has been added to the deploy gate's holdout. "
            "That drops the single unburned clean split into the gate's own population and "
            "burns it before the verdict run (D31-11)."
        )

    @pytest.mark.integration
    def test_the_scored_population_contains_no_2025_game(self) -> None:
        """Measured on live gold, which DOES carry 2025 -- so this cannot pass for free.

        TWO independent mechanisms keep 2025 out, and the test reads both. The presence
        check must therefore read the PARQUET, not the loader: ``_load_features`` is itself
        one of the two mechanisms (it drops future seasons before returning), so asking it
        whether gold contains 2025 would answer a different question and fail for the very
        reason the control is looking for. That mistake was made and corrected here rather
        than left as a green assertion pointing at the wrong frame.
        """
        _require_rescore_inputs()
        from backtest.engine import BacktestEngine
        from models.deploy_gate import HOLDOUT_SEASONS

        engine = BacktestEngine()
        for target in ("wp", "ats", "ou"):
            on_disk = pd.read_parquet(
                REPO_ROOT / "data" / "gold" / f"features_{target}.parquet",
                columns=["season"],
            )
            stored_seasons = {
                int(season) for season in on_disk["season"].dropna().unique()
            }
            assert _CLEAN_SPLIT_SEASON in stored_seasons, (
                f"{target}: gold on disk carries no {_CLEAN_SPLIT_SEASON} season, so this "
                "control would pass for free. It exists to prove the 2025 slice is "
                "EXCLUDED from the gate, which requires it to be PRESENT in gold."
            )

            # Mechanism 1: the loader drops future seasons before the gate ever sees them.
            features = engine._load_features(target)
            loaded_seasons = {
                int(season) for season in features["season"].dropna().unique()
            }
            assert _CLEAN_SPLIT_SEASON not in loaded_seasons, (
                f"{target}: BacktestEngine._load_features returned "
                f"{_CLEAN_SPLIT_SEASON} rows. The future-season filter is the first of the "
                "two mechanisms keeping the clean split out of the gate."
            )

            # Mechanism 2: the baseline population is bounded by the holdout constant.
            in_holdout = (features["season"] >= HOLDOUT_SEASONS[0]) & (
                features["season"] <= HOLDOUT_SEASONS[-1]
            )
            scored_seasons = {
                int(season)
                for season in features.loc[in_holdout, "season"].dropna().unique()
            }
            assert scored_seasons == set(_EXPECTED_HOLDOUT), (
                f"{target}: the population the gate baseline scores covers seasons "
                f"{sorted(scored_seasons)}, not {list(_EXPECTED_HOLDOUT)}."
            )


class TestEverySkipReasonThisModuleCanEmitIsRegistered:
    """A control that did not run must be NAMED in the terminal summary (WR-10)."""

    @pytest.mark.parametrize("reason", _SKIP_REASONS_THIS_MODULE_CAN_EMIT)
    def test_the_reason_is_recognised_as_evidence_backed(self, reason: str) -> None:
        from tests.conftest import is_evidence_backed_skip

        assert is_evidence_backed_skip(reason), (
            f"the skip reason {reason!r} is emitted by a control in this module but is "
            "not recognised as evidence-backed, so that control would disappear silently "
            "into a green suite. Register its phrasing in "
            "tests/conftest._EVIDENCE_SKIP_MARKERS."
        )

    def test_the_catalogue_covers_every_skip_call_site_in_this_module(self) -> None:
        """Adding a skip without cataloguing it is a failure, not an invisible non-run."""
        tree = ast.parse(Path(__file__).read_text(encoding="utf-8"))
        n_skip_calls = sum(
            1
            for node in ast.walk(tree)
            if isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "skip"
        )

        assert n_skip_calls == len(_SKIP_REASONS_THIS_MODULE_CAN_EMIT), (
            f"this module has {n_skip_calls} pytest.skip call sites but catalogues "
            f"{len(_SKIP_REASONS_THIS_MODULE_CAN_EMIT)} reasons. Every reason this module "
            "can emit must be listed in _SKIP_REASONS_THIS_MODULE_CAN_EMIT and recognised "
            "by tests/conftest.is_evidence_backed_skip."
        )
