"""SUPERSEDING CORRECTION of the 2026 EV floor and frozen residual SD recorded at 8c9675e (row 19).

GENERATED by ``scripts/derive_corrected_ev_chain.py --correction row19`` (quick task 261003-vke)
-- do not edit by hand; re-run the script.

WHAT IT SUPERSEDES. Commit ``8c9675e`` (8c9675e07644af383a8bb7817e8f126fb149de12) recorded the per-target EV floor and the
frozen residual SD in ``backtest/corrected_ev_chain_constants.py`` (run record
``outputs/p332/corrected_chain_fit.json``), measured on the three models production served from
2026-09-23. Owner ruling 2026-10-03 ~22:12 ET (WINDOWS row 19, "No home boost at any neutral
site"): Elo home-field advantage is zero at every neutral site and neutral games are left out of
HFA learning. Elo, gold and all three models were re-derived under that rule and swapped into
production on 2026-10-04, so scalars measured on the old models describe models that no longer
serve. Owner ruling 2026-10-03 ~22:50 ET ("Re-measure, same recipe"): this module is the SAME
recipe re-run, unchanged, on the new production models. The 8c9675e module and record are
byte-unchanged and remain the record of what was measured and when; nothing here edits them.

WHAT MOVED, symbol by symbol:
  * the EV floor per target -> ``CORRECTED_EV_FLOOR_BY_TARGET`` (the 8c9675e values beside it
    in ``SUPERSEDED_EV_FLOOR_BY_TARGET``). ``None`` means NO HONEST FLOOR COULD BE SWEPT and
    therefore NO BETS for that target (``CORRECTED_FLOOR_REFUSALS`` says why) -- never 0.0,
    which is a real grid value that admits everything, and never ``inf``, which
    ``assign_ev_tier`` refuses by name. Equal old and new values are a legitimate outcome of a
    re-measure: the floor is chosen from a coarse grid;
  * the frozen residual SD -> ``CORRECTED_FROZEN_SD_BY_TARGET`` (the 8c9675e values in
    ``SUPERSEDED_FROZEN_SD_BY_TARGET``); ATS and O/U only, WP none by design (D31-07);
  * the replay-snapshot policy sentence -> ``CORRECTED_REPLAY_SNAPSHOT_TS_POLICY`` (unchanged
    text, carried so this module has the 8c9675e module's shape).

WHAT DID NOT MOVE, and is READ from the frozen modules rather than re-declared here: the grid the
floor is chosen from (``backtest.ou_ev_chain.EV_FLOOR_GRID``), the ROI-best rule over it, the
frozen-SD estimator (``fit_frozen_residual_sd``), the walk-forward bias estimator and the EV tier
band edges (``backtest.ev_chain_constants.EV_TIER_BANDS``). No uppercase name in this module
repeats one defined in either frozen module.

THE ONE DELIBERATE DIVERGENCE from the Phase-31 recipe is inherited unchanged from 8c9675e: where
no grid floor admits a bet, Phase 31 froze the grid floor 0.00; this correction refuses and
records ``None``.

THE WINDOW. 2020-2024 is the whole honest corpus, not a preference: 2018-2019 are unbuyable at any price and 2025 has no free pre-lock source. The single-use 2025 hold is spent and is not re-read. The bias seed (2017-2019) is the new models' own walk-forward
residuals and feeds only the first seasons' bias. WP's first owned season has no prior-fold
converter slope, so WP is swept on 2021-2024.

NOT CLEAN EVIDENCE (D33.2-07): these are re-measured past seasons. They select a threshold; they
do not establish profitability. Only the 2026 season, recorded live, counts.

STAGED UNTIL THE ROW-19 REPOINT COMMIT: the live bet-list reader resolves the 8c9675e record
until one commit repoints it to ``outputs/row19/neutral_hfa_chain_fit.json`` together with the re-measured cold-start bias
and edge thresholds.

ASCII only, no emoji (CLAUDE.md hard constraint).
"""

from __future__ import annotations

SUPERSEDED_PREREGISTRATION_COMMIT: str = "8c9675e07644af383a8bb7817e8f126fb149de12"
CORRECTED_CHAIN_FIT_RECORD_PATH: str = "outputs/row19/neutral_hfa_chain_fit.json"
CORRECTED_CHAIN_FIT_RECORD_ID: str = "neutral_hfa_chain_fit_20261004_052326"
CORRECTED_SOURCE_ARTIFACT_IDS: dict[str, str] = {
    "wp": "wp_20261004_050223",
    "ats": "ats_20261004_050228",
    "ou": "ou_20261004_050232",
    "blend": "blend_20261004_050521",
}
CORRECTED_MARKET_PROBABILITY_ARTIFACT_ID: str = "market_probability_20260923_195443"
CORRECTED_GOLD_GENERATION: str = (
    "9ba3a56885ab3b26524d2255e73b46bf674c9b18043cd7ca2bcc74a71cab9228"
)
CORRECTED_DERIVATION_SEASONS: tuple[int, ...] = (2020, 2021, 2022, 2023, 2024)
CORRECTED_WP_DERIVATION_SEASONS: tuple[int, ...] = (2021, 2022, 2023, 2024)
CORRECTED_WP_EXCLUDED_NO_PRIOR_FOLD: int = 255
CORRECTED_BIAS_SEED_SEASONS: tuple[int, ...] = (2017, 2018, 2019)
CORRECTED_WINDOW_REASON: str = "2020-2024 is the whole honest corpus, not a preference: 2018-2019 are unbuyable at any price and 2025 has no free pre-lock source. The single-use 2025 hold is spent and is not re-read."
CORRECTED_EV_FLOOR_BY_TARGET: dict[str, float | None] = {
    "wp": 0.0,
    "ats": 0.0,
    "ou": 0.01,
}
SUPERSEDED_EV_FLOOR_BY_TARGET: dict[str, float] = {"wp": 0.0, "ats": 0.05, "ou": 0.0}
CORRECTED_FLOOR_REFUSALS: dict[str, str] = {}
CORRECTED_FROZEN_SD_BY_TARGET: dict[str, float | None] = {
    "wp": None,
    "ats": 13.42742143578699,
    "ou": 13.737115789484102,
}
SUPERSEDED_FROZEN_SD_BY_TARGET: dict[str, float | None] = {
    "wp": None,
    "ats": 13.446837941873182,
    "ou": 13.67472671184805,
}
CORRECTED_WP_NO_FROZEN_SD_REASON: str = "D31-07: WP fits no residual SD by design. A calibrated classifier has no residual to take a standard deviation of, and inventing a logit-space one was rejected (backtest/wp_ev_chain.py)."
CORRECTED_THREAD_LIMIT: int = 1
CORRECTED_WP_WIN_PAYOUT_FACTOR: float = 0.9090909090909091
CORRECTED_REPLAY_SNAPSHOT_TS_POLICY: str = "Every replay row's information time is judged against THAT GAME'S OWN LOCK: 18:00 America/New_York on the ET calendar day before its kickoff (D33.2-01, utils.game_lock). Information timed at the lock is admissible; one second after is not. This SUPERSEDES -- it does not replace -- the frozen sentence of commit ee20773 (backtest/ev_chain_constants.py), which describes the retired preceding-Friday 6 PM Eastern freeze and the retired get_synthetic_snapshot_ts; that sentence stays byte-unchanged as the record of what was frozen and when."
